---
updates:
  - allow:
      - dependency-type: all
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
version: 2
