name: Tests

on: 
  push:
  schedule:
  - cron: '27 */12 * * *'

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Test
        env:
          OMGLOL_API_KEY: ${{ secrets.OMGLOL_API_KEY }}
          OMGLOL_API_HOST: "https://api.omg.lol"
          OMGLOL_USERNAME: ${{ secrets.OMGLOL_USERNAME }}
          OMGLOL_USER_EMAIL: ${{ secrets.OMGLOL_USER_EMAIL }}
          OMGLOL_TEST_OWNED_DOMAIN: ${{ vars.OMGLOL_TEST_OWNED_DOMAIN }}
        run: go test ./...
